AllCops:
  NewCops: enable
  Exclude: 
    - /**/bin/*
    - /**/gemfiles/**

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics:
  Exclude:
    - /**/spec/**/*

Metrics/BlockLength:
  Exclude:
    - /**/spec/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
